### ISSUE TITLE
Does not work with flatex.de classic

### ISSUE THREAD

**Issue by dalgaaf** [purecopy/flatex-download-chrome-extension#10]
It seems the extension does not work anymore with the classic webinterface at flatex.de. It shows 0 documents to be available for download. Do you need any details?

**Comment by tomheinisch** [comment]
Same for flatex.at - "0 documents found" even if the filter returns documents with PDFs to download. 
![image](https://github.com/user-attachments/assets/4dcfb0b6-1d25-414c-b0f2-25fbcb83c699)

**Comment by purecopy** [comment]
I think there are some permission problems with the upcoming Chrome versions. I will have a look this evening.

Thanks for reporting the issue🙂

**Comment by tomheinisch** [comment]
> I think there are some permission problems with the upcoming Chrome versions. I will have a look this evening.
> 
> Thanks for reporting the issue🙂

Hi, were you able to identify the issue already?
Thanks!

**Comment by purecopy** [comment]
It turns out there are two issues:

1. The widget loader is failing.
2. The command structure from Flatex has changed.

EDIT: It seems like #.2 is hard to test. I will check later this week. @dalgaaf can you install the latest version@2.1.0 and give me some feedback?

I have already fixed the loading issue. Now, I will continue with adapting to the new command structure. :)
